name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Need your approval: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
          $DISCORD_WEBHOOK
  manual-approval:
    runs-on: ubuntu-latest
    needs: notification
    steps:
      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          approvers: lai85321
          minimum-approvals: 1
          
  deploy:
    runs-on: ubuntu-latest
    needs:  manual-approval
    defaults:
      run:
        working-directory: src
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1
          role-session-name: Session-GitHubActions
    
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
