name: terraform-merge-check

on:
  pull_request:
    types: [opened, reopened]
jobs:

  terraform-merge-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_role
          aws-region: ap-northeast-1
      - run: terraform init
      - run: terraform fmt
      - run: terraform validate
      - run: terraform plan
