name: terraform-merge-check

on:
  pull_request:
    types: [opened, reopened]

jobs:
  terraform-merge-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1
          role-session-name: Session-GitHubActions

      - run: terraform init
      - run: terraform fmt
      - run: terraform validate

      - name: Terraform Plan Status
        id: plan
        run: |
         terraform plan -no-color -out=plan.out
         plan_output=$(cat plan.out)
         echo "plan_output<<EOF" >> $GITHUB_OUTPUT
         echo "$plan_output" >> $GITHUB_OUTPUT
         echo "EOF" >> $GITHUB_OUTPUT
         
      - name: Terraform Plan Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const output = `#### Terraform Plan 結果
            \`\`\`diff
            ${(await getInput('plan_output')).split('\n').join('\n      ')}
            \`\`\``;
      
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
