name: terraform-merge-check

on:
  pull_request:
    types: [opened, reopened]

jobs:

  terraform-merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt
      - run: terraform validate
      - run: terraform plan
